(defparameter *small* 1)
(defparameter *big* 100)
(defun guessmynumber()
  (ash (+ *small* *big*) -1))
(defun smaller ()
  (setf *big* (1- (guessmynumber)))
  (guessmynumber))
(defun bigger ()
  (setf *small* (1+ (guessmynumber)))
  (guessmynumber))
(defun start-over ()
  (defparameter *small* 1)
  (defparameter *big* 100)
  (guessmynumber))
